package constants

const (
    ERROR_INVALID_REQUEST   = "INVALID_REQUEST"
    ERROR_UNAUTHORIZED      = "UNAUTHORIZED"
    ERROR_FORBIDDEN         = "FORBIDDEN"
    ERROR_NOT_FOUND         = "NOT_FOUND"

    ERROR_LINK_EXPIRED      = "LINK_EXPIRED"
    ERROR_LINK_NOT_ACTIVE   = "LINK_NOT_ACTIVE"
    ERROR_INVALID_PASSWORD  = "INVALID_PASSWORD"
    ERROR_INVALID_ANSWER    = "INVALID_ANSWER"
    ERROR_QUOTA_EXCEEDED    = "QUOTA_EXCEEDED"
)